### ISSUE TITLE
Consider MIT license

### ISSUE THREAD

**Issue by mgreenegit** [PowerShellOrg/tug#90]
Would you consider the MIT license?  That's been the standard for other DSC projects.

**Comment by ebekker** [comment]
I actually would welcome it, but I would need to get blessing from @concentrateddon -- he initiated the project and might have had specific rationale for going with GPL.  There was a bit of a discussion about it and a possible misunderstanding [here](https://powershell.org/2016/12/19/update-tug-the-open-source-dsc-pull-server/#comment-12390).

Don, what are your thoughts?

**Comment by concentrateddon** [comment]
I only picked GPL because it was easy :) it’s all your code at this point so whatever you’re comfy with!

On Mar 13, 2018, at 1:58 PM, Eugene Bekker <notifications@github.com<mailto:notifications@github.com>> wrote:


I actually would welcome it, but I would need to get blessing from @concentrateddon<https://github.com/concentrateddon> -- he initiated the project and might have had specific rationale for going with GPL. There was a bit of a discussion about it and a possible misunderstanding here<https://powershell.org/2016/12/19/update-tug-the-open-source-dsc-pull-server/#comment-12390>.

Don, what are your thoughts?

**Comment by ebekker** [comment]
Sounds good!

**Comment by ebekker** [comment]
Don, as part of this move, I'll also be updating all the boilerplate front matter in the source files that gives copyright attribution and license info.  Currently it reads as follows:

```csharp
/*
 * Copyright © The DevOps Collective, Inc. All rights reserved.
 * Licnesed under GNU GPL v3. See top-level LICENSE.txt for more details.
 */
```

The license comment is straight forward, but as for the copyright notice -- I searched back through the project history and I think I originally pulled the copyright notice from the [first `project.json`](https://github.com/PowerShellOrg/tug/blob/6c9b394370a614c91d93f0e914ae8022a6763e75/tug/project.json) file that you started with.

However, I noticed that this GitHub org is actually associated with **PowerShell.org, Inc.** -- should the project copyright be updated to reflect this as well?

**Comment by concentrateddon** [comment]
DevOps Collective is the company name; that wasn’t alwasy the case but we changed it in 2014 or 2015. PowerShell.org I’d just a brand at this point, but it’s hard to get GitHub to let go.

**Comment by ebekker** [comment]
Thanks Don, I'll leave the copyright attribution as it is.  Since the PowerShell.org brand is pby better known, I'm going to throw that in there as well -- so the final revised boilerplate will look like this:

```csharp
// PowerShell.org Tug DSC Pull Server
// Copyright (c) The DevOps Collective, Inc.  All rights reserved.
// Licensed under the MIT license.  See the LICENSE file in the project root for more information.
```
